version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    environment:
      REPO: michaelvl/kustomize
      KUSTOMIZE_VER: v3.5.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: |
            echo "REPO=$REPO" >> $BASH_ENV
            GITCOMMIT=${CIRCLE_SHA1::7}
            NOW=$(date +%Y%m%d-%H%M)
            FULLNAME="$REPO:$NOW-$GITCOMMIT-$KUSTOMIZE_VER"
            SHORTNAME="$REPO:$KUSTOMIZE_VER"
            echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            echo "SHORTNAME=$SHORTNAME" >> $BASH_ENV
            echo "Branch $CIRCLE_BRANCH"
            echo "Using full name $FULLNAME"
            echo "Using version $KUSTOMIZE_VER"
      - run:
          name: Build container image
          command: |
            curl -Lso kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${KUSTOMIZE_VER}/kustomize_${KUSTOMIZE_VER}_linux_amd64.tar.gz
            docker build -t $FULLNAME .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME $REPO:latest
            fi
      - run:
          name: Push container image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $REPO
